### ISSUE TITLE
Import Messages Problem

### ISSUE THREAD

**Issue by hcossio** [elhardoum/bbp-messages#1]
Hi. Just passing along to let you know:

Clicking on "click here" sends the user to the wrong url.

> bbPress Messages v2: Import older messages now from legacy data table. Click here to begin import.

Directs user to admin.php.php?page=bbpm-bbpm-import instead of admin.php?page=bbpm-bbpm-import

Keep up the great work!

**Comment by elhardoum** [comment]
Hi! Thank you so much for pointing out the issue. Fixed.
Be good :)
