### ISSUE TITLE
Proper implementation of text domain while using the gettext functions

### ISSUE THREAD

**Issue by jmslbam** [elhardoum/bbp-messages#5]
`printf( __('Send a new message to %s:', BBP_MESSAGES_DOMAIN);`

This shouldn't be working... although it does... weird.

It should be `printf( __('Send a new message to %s:', 'bbp-messages');`

Explaination by Otto, core WP dev
http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/
More info
https://ulrich.pogson.ch/string-text-domain-must

**Comment by elhardoum** [comment]
Lesson learned. [GNU gettext is not a PHP parser](https://markjaquith.wordpress.com/2011/10/06/translating-wordpress-plugins-and-themes-dont-get-clever/). Thanks man for pointing it out, I'll replace all the occurrences and push an updated, then see about your other issue and PRs.
