### ISSUE TITLE
Trans "send" button

### ISSUE THREAD

**Issue by jmslbam** [elhardoum/bbp-messages#8]
I can't translate the [Send] button
https://github.com/elhardoum/bbp-messages/blob/master/templates/widgets/new-message.php#L36

Something like 

`<input type="submit" name="send_message" value="<?php esc_attr_e('Send', BBP_MESSAGES_DOMAIN); ?>" />`

Only I don't what you would like to put in there for the `name` attribute. If the name attribute can be empty then I can create a PR for your, else just let me know.

Ciao!

**Comment by elhardoum** [comment]
The name tag attribute is not important, go ahead with the PR. Thanks in advance!
