### ISSUE TITLE
Avatars not displayed in chat list

### ISSUE THREAD

**Issue by Willemijnr** [elhardoum/bbp-messages#9]
User avatars (uploaded with basic user avatars plugin) are not showing in chat list: https://github.com/elhardoum/bbp-messages/blob/master/templates/messages/loop-chat.php#L7

It does works on messages list: https://github.com/elhardoum/bbp-messages/blob/master/templates/messages/loop-message.php#L8

**Comment by elhardoum** [comment]
This is a common problem. You see most of plugins that are for custom avatar upload opt to filter out the HTML of [`get_avatar`](https://developer.wordpress.org/reference/functions/get_avatar/
) function, leaving behind the others that are meant for retrieving the avatar data such as [`get_avatar_url`](https://developer.wordpress.org/reference/functions/get_avatar_url/
) which is in use. BuddyPress was doing the same with their custom avatars, but I pointed it out and they got it covered in their latest release (bp 2.9).

To add support for local avatars, see this wp-org support thread https://wordpress.org/support/topic/avatars-and-delete/, you'll basically want to add this custom code to your child theme's functions file (or via a custom plugin):

```php
add_filter('BBP_MESSAGES_getChatAvatar', function($avatar, $chat){
    if ( isset( $chat['recipients'] ) && count($chat['recipients']) < 3 ) {
        foreach ( $chat['recipients'] as $user_id ) {
            if ( $user_id !== bbpm_messages()->current_user ) {
                $html = get_avatar($user_id);

                preg_match('/src=["\']?(.*?)["\']?(\s|\z|>)/si', $html, $src);

                if ( !empty($src[1]) )
                    $avatar = $src[1];
            }
        }
    }

    return $avatar;
}, 10, 2);
```
